AderFber-MuseumToulouse/grails-app/domain/aderfber/museumtoulouse/AskingVisit.groovy
package aderfber.museumtoulouse

class AskingVisit {
    Integer code
    Date beginPeriodDate
    Date endPeriodDate
    int nbPeople
    int status = 0

    static constraints = {
        code nullable: false
        beginPeriodDate nullable: false
        endPeriodDate nullable: false, validator: { val, obj ->
            return val != null && obj != null && val > obj.beginPeriodDate
        }
        nbPeople min: 0, max: 6
        status inList: [0,1,2]
    }

    public String statusToString() {
        def list = ["En cours de traitement", "Accepté", "Refusé"];
        return list[status]
    }

}

AderFber-MuseumToulouse/grails-app/controllers/aderfber/museumtoulouse/AskingVisitController.groovy
package aderfber.museumtoulouse

import java.text.ParseException

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AskingVisitController {
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    StarService starService
    VisitService visitService
    boolean isCollectionOrArray(object) {
        [Collection, Object[]].any { it.isAssignableFrom(object.getClass()) }
    }
    def formList() {
        render(view: 'list', model: [])
    }

    def askingList() {
            params.code = isCollectionOrArray(params.code) ? params.code.last() : params.code as Integer
            def errors = []
            AskingVisit a = AskingVisit.findByCode(params.code as Integer);
            if(a == null) {
                errors << "ASKING_CODE";
            }
            render(view: 'list', model: [errors: errors,
                                         askingVisit: AskingMuseumVisit.findById(a?.id)])
    }

    def askingVisit() {
        Museum museum = Museum.findById(params.museumId as Long)

        if(params.beginDate && params.endDate && params.numberOfPeople) {
            boolean isValide = true
            Date begin = new Date()
            Date end = new Date()
            AskingVisit a
            params.beginDate = isCollectionOrArray(params.beginDate) ? params.beginDate.last() : params.beginDate as String
            params.endDate = isCollectionOrArray(params.endDate) ? params.endDate.last() : params.endDate as String
            params.numberOfPeople = isCollectionOrArray(params.numberOfPeople) ? params.numberOfPeople.last() : params.numberOfPeople as Integer
            try {
                begin = begin.parse("dd/MM/yyyy", params.beginDate as String)
                end   = end.parse("dd/MM/yyyy", params.endDate as String)
                Integer numberOfPeople = params.numberOfPeople as Integer;
                a = new AskingVisit(beginPeriodDate: begin, endPeriodDate: end, nbPeople: numberOfPeople)
                a.code = AskingVisit.findAll().size()+1
            } catch(RuntimeException e) {
                isValide = false
                a = new AskingVisit()
            }

            if(a.validate() && isValide) { // Forms is valide
                visitService.insertOrUpdateAskingMuseumVisit(a, museum, new Date())
                render(view: '/index', model: [successes: [a], stars      : starService.stars, museum: museum,
                                               postalCodes: Address.list([sort: "postalCode", order: "asc"]).postalCode.unique()])
            } else { // Unvalide forms
                render(view: 'index', model: [errors: ["UNVALID_ASKING_VISIT"], params: params,
                                              stars      : starService.stars, museum: Museum.findById(params.museumId as Long),
                                              postalCodes: Address.list([sort: "postalCode", order: "asc"]).postalCode.unique()])
            }
        } else { // Empty forms
            render(view: 'index', model: [stars      : starService.stars, museum: Museum.findById(params.museumId as Long),
                                          postalCodes: Address.list([sort: "postalCode", order: "asc"]).postalCode.unique()])
        }
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AskingVisit.list(params), model: [askingVisitInstanceCount: AskingVisit.count()]
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(
                        code: 'default.not.found.message',
                        args: [message(code: 'askingVisit.label',
                                default: 'AskingVisit'),
                               params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

AderFber-MuseumToulouse/grails-app/views/askingVisit/_askingListVisitForm.gsp
<h3>Retrouver ma demande de visite</h3>
<g:form name="askingVisit" url="[controller: 'askingVisit', action:'askingList', params:params]">
    <div class="row">
        <div class="form-group">
            <input required="required"
                   name="code"
                   id="code"
                   class="form-control input-lg"
                   placeholder="Code de la visite" tabindex="1" value="" type="number" min="0">
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary"><i class="glyphicon glyphicon-search"></i>&nbsp;Chercher une demande de visite</button>
    </div>

</g:form>

AderFber-MuseumToulouse/grails-app/views/askingVisit/_askingVisitForm.gsp
<h3>Visiter le musée ${museum.name}</h3>
<div class="alert alert-warning">
    <p>Le nombre de personnes inscrites à la visite ne peux excéder 6 personnes.</p>
</div>
<g:form name="askingVisit" url="[controller: 'askingVisit', action:'askingVisit', params:params]">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
                <div required="required" class="input-group date input-group-lg" id="beginDate">
                    <input data-date-format="DD/MM/YYYY" tabindex="1" id="beginDate" name="beginDate" placeholder="Date de début" class="form-control input-lg" value="" type="text">
                    <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span>
                    </span>
                </div>
            </div>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
                <div required="required" class="input-group date input-group-lg" id="endDate">
                    <input data-date-format="DD/MM/YYYY" tabindex="2" id="endDate" name="endDate" placeholder="Date de fin" class="form-control input-lg" value="" type="text">
                    <span class="input-group-addon"><span class="glyphicon-calendar glyphicon"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <input required="required"
                   name="numberOfPeople"
                   id="numberOfPeople"
                   class="form-control input-lg"
                   placeholder="Nombre de personnes" tabindex="2" value="" type="number" max="6" min="1">
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="form-group">
        <button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i>&nbsp;Demander une visite</button>
    </div>
</g:form>

<script type="text/javascript">
    $(document).ready(function() {
        $('#beginDate').datetimepicker({
            pickTime: false
        });
        $('#endDate').datetimepicker({
            pickTime: false
        });
    });
</script>

AderFber-MuseumToulouse/grails-app/views/askingVisit/index.gsp
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main"/>
	<title>Toulouse-Musees</title>
</head>
<body>
<div class="jumbotron">
	<h2>Demander à visiter un musée</h2>
	<p style="font-size: 12pt">Vous pouvez visiter les musées que vous souhaitez, il suffit de remplir le formulaire !
	</p>
</div>

<g id="controller-list" role="navigation">
	<div class="row">
		<g:if test="${errors}">
		<div class="alert alert-danger">
			<g:each in="${errors}" var="${error}">
				<g:if test="${error} == 'UNVALID_ASKING_VISIT'">
					<b>Erreur</b> Une erreur a eu lieu pendant l'ajout de la demande de visite : votre formulaire est invalide.
				</g:if>
			</g:each>
		</div>
		</g:if>
		<div class="col-md-7 ">
			<g:render template="askingVisitForm" model="[ museum:museum, params:params  ]" />
		</div>
		</div>
		<div class="col-md-offset-1 col-md-4">
			<g:render template="/stars/list" model="[ stars : stars ]" />
		</div>
	</div>

</g>
</body>
</html>

AderFber-MuseumToulouse/grails-app/views/askingVisit/list.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Toulouse-Musees</title>
</head>
<body>
<div class="jumbotron">
    <h2>Retrouver une demande de visite</h2>
    <p style="font-size: 12pt">Il vous suffit d'avoir le code de la demande pour retrouver son avancement !
    </p>
</div>

<g id="controller-list" role="navigation">
    <div class="row">
        <g:if test="${errors}">
            <div class="alert alert-danger">
                <g:each in="${errors}" var="${error}">
                    <g:if test="${error} == 'ASKING_CODE'">
                        <b>Erreur</b> Le numéro de visite est inconnu
                    </g:if>
                </g:each>
            </div>
        </g:if>
        <g:if test="${askingVisit}">
            <h3>Demande de visite pour « ${askingVisit.museum.name} »</h3>
            <p><em>Demande du <g:formatDate format="dd/MM/yyyy à HH:mm" date="${askingVisit.askingDate}"/></em></p>
            <ul>
                <li><b>Date de début</b> <g:formatDate format="dd/MM/yyyy" date="${askingVisit.askingVisit.beginPeriodDate}"/></li>
                <li><b>Date de fin</b> <g:formatDate format="dd/MM/yyyy" date="${askingVisit.askingVisit.endPeriodDate}"/></li>
                <li><b>Nombre de personnes</b> ${askingVisit.askingVisit.nbPeople}</li>
                <li><b>Statut</b> ${askingVisit.askingVisit.statusToString()}</li>
            </ul>
        </g:if>
        <g:else>
            <div class="col-md-7 ">
                <g:render template="askingListVisitForm" />
            </div>
        </g:else>
    </div>
</div>

</g>
</body>
</html>

AderFber-MuseumToulouse/grails-app/views/askingVisit/show.gsp
<%@ page import="aderfber.museumtoulouse.AskingVisit" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'askingVisit.label', default: 'AskingVisit')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-askingVisit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-askingVisit" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list askingVisit">
			
				<g:if test="${askingVisitInstance?.code}">
				<li class="fieldcontain">
					<span id="code-label" class="property-label"><g:message code="askingVisit.code.label" default="Code" /></span>
					
						<span class="property-value" aria-labelledby="code-label"><g:fieldValue bean="${askingVisitInstance}" field="code"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${askingVisitInstance?.beginPeriodDate}">
				<li class="fieldcontain">
					<span id="beginPeriodDate-label" class="property-label"><g:message code="askingVisit.beginPeriodDate.label" default="Begin Period Date" /></span>
					
						<span class="property-value" aria-labelledby="beginPeriodDate-label"><g:formatDate date="${askingVisitInstance?.beginPeriodDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${askingVisitInstance?.endPeriodDate}">
				<li class="fieldcontain">
					<span id="endPeriodDate-label" class="property-label"><g:message code="askingVisit.endPeriodDate.label" default="End Period Date" /></span>
					
						<span class="property-value" aria-labelledby="endPeriodDate-label"><g:formatDate date="${askingVisitInstance?.endPeriodDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${askingVisitInstance?.nbPeople}">
				<li class="fieldcontain">
					<span id="nbPeople-label" class="property-label"><g:message code="askingVisit.nbPeople.label" default="Nb People" /></span>
					
						<span class="property-value" aria-labelledby="nbPeople-label"><g:fieldValue bean="${askingVisitInstance}" field="nbPeople"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${askingVisitInstance?.status}">
				<li class="fieldcontain">
					<span id="status-label" class="property-label"><g:message code="askingVisit.status.label" default="Status" /></span>
					
						<span class="property-value" aria-labelledby="status-label"><g:fieldValue bean="${askingVisitInstance}" field="status"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:askingVisitInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${askingVisitInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>