AderFber-MuseumToulouse/grails-app/domain/aderfber/museumtoulouse/Museum.groovy
package aderfber.museumtoulouse

class Museum {
    String name
    String openingHours
    String phone
    String subwayAccess
    String busAccess
    Address address
    Manager manager

    static constraints = {
        name blank : false
        openingHours blank: false
        phone blank: true, nullable: true
        subwayAccess blank : true, nullable: true
        busAccess blank : true, nullable: true
        address nullable: false
        manager nullable: false
    }

    public String getName() {
        return name?.toLowerCase()?.capitalize()
    }

    static mapping = {
        manager fetch: 'join'
        address fetch: 'join'
    }

}

AderFber-MuseumToulouse/grails-app/controllers/aderfber/museumtoulouse/MuseumController.groovy
package aderfber.museumtoulouse


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class MuseumController {
    /**
     * Museum service.
     */
    MuseumService museumService

    /**
     * Stars service.
     */
    StarService starService

    /**
     * Methods to trnasfert data.
     */
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    /**
     * Search museums according filters with <i>max</i> elements per page.
     * @param max Elements max per page
     * @return new view.
     */
    def doResearch(Integer max) {
        String name = params.name
        String postalCode = params.postalCode
        String address = params.address

        params.max = max ?: 5
        params.offset = params.offset ?: 0
        max = params.max
        int offset = params.offset.toInteger();
        int lastElement = max + offset

        List<String> postalCodes = Address.list([sort: "postalCode", order: "asc"]).postalCode.unique();
        List<Museum> museums = museumService.searchMuseums(name, address, postalCode)

        lastElement = lastElement <= museums.size() ? lastElement : museums.size()

        render(view: '/index', model: [museums: museums.subList(offset, lastElement), museumsCount: museums.size(),
                                       postalCodes: postalCodes, params:params,
                                       stars: starService.stars,
                                      successToStars: params.successToStars,
                                       successUnstars: params.successUnstars])
    }

    /**
     * Search a Museum by Id.
     * @return new veiw of the museum
     */
    def doRsearchById() {
        Museum m = Museum.findById(params['museumId'] as Long)
        museumService.searchMuseums(
                m.name.toString(),
                m.address.street,
                m.address.postalCode)
        render(view: '/index', model: [museums: [m], museumsCount: 1,
                                       postalCodes: m.address.postalCode,
                                       params:params,
                                       stars: starService.stars])

    }

    /**
     * Return new view to sort by postal code museums in the list of stars
     * @param max Max elements
     * @return view
     */
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        render(view: '/index', model: [stars: starService.stars,
                                       postalCodes: Address.list([sort: "postalCode", order: "asc"]).postalCode.unique()])
    }

    /**
     * Show an Instance of Museum <i>museumInstance</i>
     * @param museumInstance Instance of Museum
     * @return Instance of Museum
     */
    def show() {
        render(view: 'show', model: [stars: starService.stars, museum: Museum.findById(params.museumId as Long),
                                       postalCodes: Address.list([sort: "postalCode", order: "asc"]).postalCode.unique()])

    }

    /**
     * Create a new Museum and return it
     * @return
     */
    def create() {
        respond new Museum(params)
    }

    /**
     * Save in database the Museum <i>museumInstance</i>
     * @param museumInstance Instance of Museum
     * @return Instance of Museum
     */
    @Transactional
    def save(Museum museumInstance) {
        if (museumInstance == null) {
            notFound()
            return
        }

        if (museumInstance.hasErrors()) {
            respond museumInstance.errors, view: 'create'
            return
        }

        //Address address = Address.get(museumInstance.address.id)
        //Manager manager = Manager.get(museumInstance.manager.id)
        museumService.insertOrUpdateMuseum(
                museumInstance,
                museumInstance.address,
                museumInstance.manager)
        //museumInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message',
                                    args: [message(code: 'museum.label',
                                    default: 'Museum'), museumInstance.id])
                redirect museumInstance
            }
            '*' { respond museumInstance, [status: CREATED] }
        }
    }

    /**
     * Change the current Museum by the new <i>museumInstance</i>
     * @param museumInstance
     * @return Instance of Museum
     */
    def edit(Museum museumInstance) {
        respond museumInstance
    }

    /**
     * Update Instance of Museum <i>museumInstance</i>
     * @param museumInstance Instance of Museum
     * @return Museum Instance
     */
    @Transactional
    def update(Museum museumInstance) {
        if (museumInstance == null) {
            notFound()
            return
        }

        if (museumInstance.hasErrors()) {
            respond museumInstance.errors, view: 'edit'
            return
        }
        Address address = Address.get(museumInstance.address.id)
        Manager manager = Manager.get(museumInstance.manager.id)
        museumService.insertOrUpdateMuseum(museumInstance,address,manager)
        //museumInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message =
                        message(code: 'default.updated.message',
                                args: [message(code: 'Museum.label',
                                default: 'Museum'), museumInstance.id])
                redirect museumInstance
            }
            '*' { respond museumInstance, [status: OK] }
        }

    }

    /**
     * Remove the museum <i>museumInstance</i>
     * @param museumInstance Instance of Museum
     * @return Instance of Museum
     */
    @Transactional
    def delete(Museum museumInstance) {

        if (museumInstance == null) {
            notFound()
            return
        }

        museumService.deleteMuseum(museumInstance)
        //museumInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message =
                        message(code: 'default.deleted.message',
                                args: [message(code: 'Museum.label',
                                default: 'Museum'), museumInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }

    }

    /**
     *
     */
    protected void notFound() {

        request.withFormat {
            form multipartForm {
                flash.message =
                        message(code: 'default.not.found.message',
                                args: [message(code: 'museum.label',
                                default: 'Museum'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }

    }
}

AderFber-MuseumToulouse/grails-app/controllers/aderfber/museumtoulouse/StarController.groovy
package aderfber.museumtoulouse

import grails.transaction.Transactional

@Transactional
class StarController {

    static sessionScope = "favori"

    /**
     * Star service to manage museum stars of user.
     */
    StarService starService

    /**
     * Add the museum <i>m</i>  to the stars list.
     * @param m Museum
     * @return stars list
     */
    def addToStars() {
        starService.addStar(Museum.findById(params['museumId'] as Long))
        redirect(controller: "museum", action: "doResearch", params: [successToStars: 1])
    }

    /**
     * Remove the museum <i>m</i>  to the stars list.
     * @param m Museum
     * @return stars list
     */
    def removeToStars() {
        starService.removeStar(Museum.findById(params['museumId'] as Long))
        redirect(controller: "museum", action: "doResearch", params: [successUnstars: 1])
    }


    /**
     * Return TRUE if the museum <i>m</i> has already added to list of stars,
     * else return FALSE
     * @param m Museum
     * @return boolean
     */
    boolean isStar(Museum m) {
        return starService.isStar(m)
    }



}

AderFber-MuseumToulouse/grails-app/views/museum/_list.gsp
<g:if test="${museums}">
    <div class="pagination">
        <g:paginate total="${museumsCount}" action="doResearch" params="${params}"/>
    </div>
    <table class="table table-striped">
        <tr>
            <th class="col-md-3">Nom du musée</th>
            <th class="col-md-2">Horaires d'ouverture</th>
            <th class="col-md-2">Téléphone</th>
            <th class="col-md-2">Adresse</th>
            <th class="col-md-1">Accès bus</th>
            <th class="col-md-2">Accès métro</th>
            <th class="col-md-2">Gestionnaire</th>
            <th class="col-md-2">Favoris</th>
        </tr>
        <g:each var="museum" in="${museums}" params="${params}">
            <tr>
                <td>${museum.name}</td>
                <td>${museum.openingHours}</td>
                <td>${museum.phone}</td>
                <td>${museum.address.street} <br/>
                    ${museum.address.postalCode} ${museum.address.city}
                </td>
                <td>${museum.busAccess}</td>
                <td>${museum.subwayAccess}</td>
                <td>${museum.manager.name}</td>
                <td>
                    <g:if test="${!stars*.id.contains(museum.id)}">
                        <g:link controller="star" action="addToStars" params="[museumId:museum.id]">
                            <button class="btn btn-primary">
                                <i class="glyphicon glyphicon-star"></i>&nbsp;Ajouter
                            </button>
                        </g:link>
                    </g:if>
                    <g:else>
                        <g:link controller="star" action="removeToStars" params="[museumId:museum.id]">
                            <button class="btn btn-default">
                                <i class="glyphicon glyphicon-star-empty"></i>&nbsp;Retirer
                            </button>
                        </g:link>
                    </g:else>
                </td>
            </tr>
        </g:each>
    </table>
    <div class="pagination">
        <g:paginate total="${museumsCount}" action="doResearch" params="${params}"/>
    </div>
</g:if>

AderFber-MuseumToulouse/grails-app/views/museum/_searchForm.gsp
<h3>Rechercher un musée</h3>

<g:form name="search" url="[controller: 'museum', action:'doResearch']">
    <div class="row">
        <div class="form-group">
            <input name="name" id="name" class="form-control input-lg" placeholder="Nom ou partie du nom" tabindex="1" value="" type="text">
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
                <select style="display: none;" tabindex="2" class="selectpicker form-control input-lg" id="postalCode" name="postalCode">
                    <option disabled="" selected="">Code postal</option>
                    <g:each var="postalCode" in="${postalCodes}">
                        <option value="${postalCode}">${postalCode}</option>
                    </g:each>
                </select>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
                <input name="address" id="address" class="form-control input-lg" placeholder="Adresse" tabindex="3" value="" type="text">
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
    <div class="form-group">
        <button class="btn btn-primary"><i class="glyphicon glyphicon-search"></i>&nbsp;Rechercher</button>
    </div>
</g:form>

AderFber-MuseumToulouse/grails-app/views/museum/_show.gsp
<div>
    <h3>
        <g:if test="${isStared}"><i class="glyphicon glyphicon-star"></i></g:if>
        <g:else><i class="glyphicon glyphicon-star-empty"></i></g:else>
        &nbsp;${museum.name}
    </h3>

    <g:if test="${isStared}">
    <g:link controller="askingVisit" action="askingVisit" params="[museumId:museum.id]">
        <button class="btn btn-primary">
            <i class="glyphicon glyphicon-plus"></i>&nbsp;Demander à visiter ce musée
        </button>
    </g:link>
    </g:if>
    <h4>Contact</h4>
    <ul style="list-style-type: none">
    <li><b><i class="glyphicon glyphicon-phone-alt"></i>&nbsp;Téléphone</b> ${museum.phone}</li>
    <li><b>Gestionnaire</b> ${museum.manager.name}</li>
    </ul>

    <h4>S'y rendre</h4>
    <ul style="list-style-type: none">
    <li><b>Horaire d'ouverture</b> ${museum.openingHours}</li>
    <li><b>Adresse</b> ${museum.address.street} ${museum.address.postalCode} ${museum.address.city}</li>
    <li><b>Accès Bus</b> ${museum.busAccess}</li>
    <li><b>Accès Métro</b> ${museum.subwayAccess}</li>
    </ul>

</div>

AderFber-MuseumToulouse/grails-app/views/museum/show.gsp
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main"/>
	<title>Toulouse-Musees</title>
</head>
<body>
<div class="jumbotron">
	<h2>Voir un musée</h2>
	<p style="font-size: 12pt">Vous pouvez voir les informations du musée, et si vous le souhaitez demander à le visiter !
	</p>
</div>

<g id="controller-list" role="navigation">
	<div class="row">
		<div class="col-md-7 ">
			<g:render template="/museum/searchForm" model="[ postalCodes: postalCodes]" />
		</div>
		</div>
		<div class="col-md-offset-1 col-md-4">
			<g:render template="/stars/list" model="[ stars : stars ]" />
		</div>
	</div>
	<g:render template="/museum/show" model="[ museum : museum, isStared: stars*.id.contains(museum.id)]" />

</g>
</body>
</html>